### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by anantgamer** [AcK77/Ryujinx-Settings#1]
What are the build instructions? Can't build it with git. Error appears. Sorry, I know it's a noob question.

**Comment by AcK77** [comment]
Hi, you have to open the .csproj file with Visual Studio and build it... 
Git is not for build projects. 

At least, in his current state, this project is not compliant with the last version of Ryujinx...

**Comment by anantgamer** [comment]
Thanks a lot, you responded literally minutes after I asked!
